### PR TITLE
Fixes two little issues

### PR DESCRIPTION
**Pull request by ObjSal**
1. Fixed a bug where is was showing unpublished articles
2. Increased the number of knowledge base topics per page to 99

### CODE REVIEW

**Comment by austintaylor** [comment]
These are good ideas.

Note that unpublished articles would only show up if you are signed in as an admin on the account. However, it does make sense to only show what end users will see.

Upping the page size on topics seems like a pretty good solution to the limited-topics-on-the-portal-screen issue. Is there a reason you went with 99? I believe the maximum page size is 100. Of course, most accounts will not have that many topics!

**Comment by ObjSal** [comment]
Hello @austintaylor, thanks for the reply!

I was not signed in as an admin on the account, I'm using the regular configuration using the website, key and secret:

    [UVConfig configWithSite:UVSite andKey:UVKey andSecret:UVSecret];

and yes I used 99 just as a random number, we are currently using no more than 20 topics, but I'm glad I was very close :)

**Comment by austintaylor** [comment]
You must be using a "trusted" client key, then. I would recommend using an untrusted client for the iOS SDK.

**Comment by austintaylor** [comment]
Merged.

**Comment by mudiam** [comment]
@austintaylor  Thanks for merging. We, TrimbleOutdoors, certainly appreciate it. We also love using uservoice in our platforms.  I assume that you will pass on this info to your Android SDK folks as well to see if there is an issue to be addressed there as well.

**Pull request closed without merging**
