### PR TITLE
TWEAK: Sync clock with server time to avoid oauth errors if they don't match

### PR DESCRIPTION
**Pull request by austintaylor**
AR-683

See testing instructions in backend PR.

Note: I added a line to force https in all cases so that I could run this against staging. This line will be removed before merging.

### CODE REVIEW

**Comment by banane** [comment]
Oh, so this is the implementation of syncing the timestamp if it doesn't work the first time?

**Comment by austintaylor** [comment]
Yes

**Comment by banane** [comment]
were you able to recreate it?

**Comment by austintaylor** [comment]
@banane Yes. See repro steps in the other PR.

**Pull request merged**
